import os

DB_USER_NAME = "EMAIL_HR"
DB_PASSWORD = os.environ.get("EMAIL_HR_DB_PASS")
HOST_NAME = "localhost"
DB_NAME = "EMAIL_JOBS"
PORT_NAME = "3306"
TABLE_NAME = "HR_DETAILS"
TEST_TABLE_NAME = "TEST_HR_DETAILS"