# email_subject: "Enthusiastic Data Professional Eager to Join {}'s Dynamic Team"
email_subject: "Application for Data Engineer Role at {}"
#  email_subject: "Application for Grader Role"
# User related variables:
personal_details:
  first_name: Amey
  last_name: Bhilegaonkar
  no_of_emails: 3
  interest: "Data Engineering and Data Science"
  prev_title_1: "Data Science Intern"
  prev_title: "Data Engineer - 2"
  prev_company: "Publicis Sapient"
  exp_in_years: 3+
  github_url: https://linkedin.com/in/amey-bhilegaonkar
  portfolio_url: https://ameyportfolio.netlify.app
  certification_url: https://www.credential.net/c799d945-5e89-47a3-845e-8b97575a8342
  soft_skills: "a Collaborative working style, a Proactive and Critical mindset"
  technical_skills:
    bullet_1: "Python, SQL, Scalable ETL Pipeline Designing"
    # bullet_3: "Kafka, AWS Kinesis, AWS SQS, GCP Pub-Sub, and GCP Dataflow"
    bullet_3: "Data Engineering tools like Kafka, Airflow, Apache Spark and BigQuery"
    bullet_4: "CICD, DevOps, and Docker"
    # Position Details - Will go in Email Body
  applying_for: Full Time
education_details:
  current_major: Computer Science
  current_gpa: "4.0/4.0"
  prev_major: Electronics and Telecommunications
  prev_gpa: "8.78/10.00"
  subjects_taken: 
    - "CSE 575: Statistical Machine Learning"
    - "CSE 594: Spatial Data Science"
    - "CSE 543: Information Assurance and Security"
    - "CSE 511: Data Processing at Scale"
    - "CSE 572: Data Mining"
    - "CSE 579: Knowledge Representation"

# Attachment Related Information
attachments_folder: Data
resume_folder: Resume
transcripts_folder: Transcripts
be_folder: be
ms_folder: ms
cover_letter_folder: CoverLetter

# This is the resume_file_name variable
resume_file_name: "{{ first_name }}_{{ last_name }}_Resume.pdf"
cover_letter_file_name: "{{ first_name }}_{{ last_name }}_Cover_Letter.pdf"
ms_transcripts_name: "{{ first_name }}_{{ last_name }}_MS_Transcripts.pdf"
be_transcripts_name: "{{ first_name }}_{{ last_name }}_BE_Transcripts.pdf"

attach_resume: True
attach_cover_letter: False
attach_ms_transcripts: False
attach_bs_transcripts: False

# Whom to send> - At a time only one be true
fetch_recruiters: True
fetch_developers: False
fetch_teachers: False
send_follow_up: False
send_thank_you: False

# Send it to any specific company? - Specify Company is the flas is set to True
send_to_specific_company: False
company_name: Navan
job_link:   
  - https://navan.com/careers/openings/5382869?gh_jid=5382869&gh_src=Simplify